### ISSUE TITLE
_experiment.sh has very minor bug

### ISSUE THREAD

**Issue by davidhoover** [rbouckaert/benchmark#1]
The subdirectory test_xml should either be created before the cd step:
# !/bin/bash

mkdir singleThread
mkdir singleThread/test_xml
cd singleThread

or without the dirname
# !/bin/bash

mkdir singleThread
cd singleThread
mkdir test_xml

**Comment by rbouckaert** [comment]
@davidhoover The benchmarks are now maintained here:
https://github.com/CompEvol/benchmark
I copied the issue there.
